apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

resources:
  - deployment.yaml

images:
  - name: argocd-testapp
    newName: 293503039498.dkr.ecr.eu-central-1.amazonaws.com/argocd-testapp
    newTag: latest

replicas:
  - name: argocd-testapp
    count: 3
